/*
 * Copyright 2020 WanYun Corporation. All Rights Reserved.
 */
package com.wanyun.sfseal.db.mapper.reference;

import com.wanyun.sfseal.db.model.reference.ReferenceDataModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @author WanYun
 */
@Repository
public interface ReferenceDataModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qucamp_reference.reference_data
     *
     * @param id the id
     * @return int
     * @mbggenerated Wed Feb 05 00:10:30 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qucamp_reference.reference_data
     *
     * @param record the record
     * @return int
     * @mbggenerated Wed Feb 05 00:10:30 CST 2020
     */
    int insert(ReferenceDataModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qucamp_reference.reference_data
     *
     * @param id the id
     * @return ReferenceDataModel
     * @mbggenerated Wed Feb 05 00:10:30 CST 2020
     */
    ReferenceDataModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qucamp_reference.reference_data
     *
     * @return List<ReferenceDataModel>
     * @mbggenerated Wed Feb 05 00:10:30 CST 2020
     */
    List<ReferenceDataModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qucamp_reference.reference_data
     *
     * @param record the record
     * @return int
     * @mbggenerated Wed Feb 05 00:10:30 CST 2020
     */
    int updateByPrimaryKey(ReferenceDataModel record);

    /**
     * Get reference data by key and category
     *
     * @param key
     * @param category
     * @return
     */
    ReferenceDataModel getReferenceDataByKeyAndCategory(@Param("key") String key, @Param("category") String category);

    /**
     * Get reference data by category
     *
     * @param category the category
     * @return List<ReferenceDataModel>
     */
    List<ReferenceDataModel> getReferenceDataByCategory(@Param("category") String category);

    /**
     * Get reference data by language
     *
     * @param language the language
     * @return List<ReferenceDataModel>
     */
    List<ReferenceDataModel> getReferenceDataByLanguage(@Param("language") Integer language);

}
